[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["tank_env"]

[project]
name = "tank_env"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "gymnasium",
  "pygame>=2.1.3",
]
